
##############################
# Country definition for ECU #
##############################

province =
{ id         = 814
  naval_base = { size = 3 current_size = 3 }
}     
 province =
{ id         = 815
  anti_air   = 2
  air_base   = { size = 1 current_size = 1 }
}      

##############################
# Country definition for PRU #
##############################

province =
{ id         = 830
  anti_air   = 2
  naval_base = { size = 3 current_size = 3 }
  air_base   = { size = 1 current_size = 1 }
}              # Lima

province = 
{ id = 2049
	anti_air = 1
	air_base = { size = 2 current_size = 2 }
	} #Chiclayo

province = 
{ id = 3825
	air_base = { size = 1 current_size = 1 }
	} #Piura

