
###############################
# Victory points distribution #
###############################

# example province = { id = 9 points = 5 } # Glasgow

#Ecuador(21)
province = { id = 3822 points = 2 } # Pantoja
province = { id = 3823 points = 2 } # Arabella
province = { id = 1835 points = 2 } # Andoas
province = { id = 814 points = 3 } # Guayaquil
province = { id = 815 points = 4 } # Quito
province = { id = 3782 points = 1 } # Santo Domingo
province = { id = 3783 points = 1 } # Manta
province = { id = 3781 points = 1 } # Cuenca
province = { id = 3784 points = 1 } # Loja
province = { id = 3787 points = 1 } # Pto. Francisco
province = { id = 3786 points = 1 } # Tena
province = { id = 817 points = 1 } # Puyo
province = { id = 3785 points = 1 } # Macas

#Peru (8)
province = { id = 3825 points = 2 } # Piura
province = { id = 818 points = 2 } # Iquitos
province = { id = 816 points = 2 } # Trujillo
province = { id = 830 points = 2 } # Lima
province = { id = 908 points = 1 } # Jaén
province = { id = 3824 points = 1 } # Borja